# Introduction To NumPy...

    >_ NumPy, Numerical Python.

    >_ Faster then normal python lists, Useful in ML calculations..

In [25]:
import numpy as np

# 1. Datatypes & Attributes ;

    >_  NumPy has only one datatype named " ndarray ".

    >_ " ndarray " means, n dimentional array..

In [26]:
ArrayOne = np.array([1, 2, 3])
ArrayOne

array([1, 2, 3])

In [27]:
type(ArrayOne)

numpy.ndarray

In [28]:
ArrayTwo = np.array([[1 , 2, 3],
                     [4, 5, 6]])
ArrayTwo

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
type(ArrayTwo)

numpy.ndarray

In [30]:
ArrayTwo.shape

(2, 3)

In [45]:
ArrayThree = np.array([[[9.0, 8, 7],
                        [6, 5.0, 4],
                        [3, 2, 1.0]]])
ArrayThree

array([[[9., 8., 7.],
        [6., 5., 4.],
        [3., 2., 1.]]])

In [46]:
ArrayThree.shape

(1, 3, 3)

In [47]:
ArrayFour = np.array([[[3, 6, 9],
                        [9, 6, 3],
                        [6, 9, 3]],
                        
                        [[33, 66, 99],
                        [99,66,33],
                        [66, 99, 33]]])

# ArrayFour
ArrayFour.shape

(2, 3, 3)

In [48]:
ArrayOne

array([1, 2, 3])

In [49]:
ArrayTwo

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
ArrayThree

array([[[9., 8., 7.],
        [6., 5., 4.],
        [3., 2., 1.]]])

In [51]:
ArrayFour
# ArrayFour.shape

array([[[ 3,  6,  9],
        [ 9,  6,  3],
        [ 6,  9,  3]],

       [[33, 66, 99],
        [99, 66, 33],
        [66, 99, 33]]])

# Some NumPy function/attributes...

In [54]:
ArrayOne.ndim, ArrayTwo.ndim, ArrayThree.ndim, ArrayFour.ndim

(1, 2, 3, 3)

In [55]:
ArrayOne.dtype, ArrayTwo.dtype, ArrayThree.dtype, ArrayFour.dtype

(dtype('int64'), dtype('int64'), dtype('float64'), dtype('int64'))

In [56]:
ArrayOne.size, ArrayTwo.size, ArrayThree.size, ArrayFour.size

(3, 6, 9, 18)

In [57]:
type(ArrayOne), type(ArrayTwo), type(ArrayThree), type(ArrayFour)

(numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray)

# Creating pandas's DataFrame from NumPy's ndarray

In [64]:
import pandas

## >_ You must pass 2d array

In [68]:
DataFrameOne = pandas.DataFrame(ArrayTwo)
DataFrameOne

0  1  2
0  1  2  3
1  4  5  6

# 2. Creating Arrays...